print("---= Built-In Functions =---")

print("--= Functional Programming =--")
print("-- map() --")
print("-- filter() --")
print("-- reduce() --")

print("--= Numeric Types Conversions and Constructors =--")
print("-- bool() --")
print("-- int() --")
print("-- long() --")
print("-- float() --")
print("-- complex() --")

print("--= Numeric Types Conversions =--")
print("-- bin() --")
print("-- oct() --")
print("-- hex() --")

print("--= Arithmetic =--")
print("-- abs() --")
print("-- pow() --")
print("-- round() --")
print("-- divmod() --")

print("--= String Conversions =--")
print("-- chr() --")
print("-- ord() --")
print("-- unichr() --")
print("-- format() --")
print("-- repr() --")

print("--= Sequences Constructors =--")
print("-- str() --")
print("-- unicode() --")
print("-- list() --")
print("-- tuple() --")
print("-- bytearray() --")
print("-- buffer() --")
print("-- memoryview() --")
print("-- range() --")
print("-- xrange() --")

print("--= Mappings Constructors =--")
print("-- dict() --")
print("-- set() --")
print("-- frozenset() --")

print("--= Operating on Containers =--")
print("-- enumerate() --")
print("-- len() --")
print("-- reversed() --")
print("-- sorted() --")
print("-- sum() --")
print("-- zip() --")
print("-- slice() --")

print("--= Iterators =--")
print("-- iter() --")
print("-- next() --")

print("--= Comparisons =--")
print("-- cmp() --")
print("-- max() --")
print("-- min() --")
print("-- all() --")
print("-- any() --")

print("--= Identity =--")
print("-- hash() --")
print("-- id() --")

print("--= File Objects Constructors =--")
print("-- file() --")
print("-- open() --")

print("--= Operating on Containers =--")
print("-- classmethod() --")
print("-- property() --")
print("-- staticmethod() --")
print("-- super() --")
print("-- setattr() --")
print("-- getattr() --")
print("-- delattr() --")
print("-- hasattr() --")
print("-- isinstance() --")
print("-- issubclass() --")
print("-- vars() --")
print("-- dir() --")
print("-- type(1)() --")
print("-- type(2)() --")

print("--= Information =--")
print("-- callable() --")
print("-- globals() --")
print("-- locals() --")
print("-- help() --")

print("--= System =--")
print("-- __import__ --")
print("-- reload() --")
print("-- compile() --")
print("-- execfile() --")
print("-- eval() --")
print("-- input() --")
print("-- intern() --")
print("-- print() --")
print("-- raw_input() --")

print("--= Input =--")
print("-- object() --")
print("-- apply() --")
print("-- basestring() --")
print("-- coerce() --")